In [43]:
import numpy as np
data_orig = np.loadtxt('a2_data/data_banknote_authentication.txt', delimiter=',')

In [44]:
print(data_orig)

[[  3.6216    8.6661   -2.8073   -0.44699   0.     ]
 [  4.5459    8.1674   -2.4586   -1.4621    0.     ]
 [  3.866    -2.6383    1.9242    0.10645   0.     ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771    1.     ]
 [ -3.5637   -8.3827   12.393    -1.2823    1.     ]
 [ -2.5419   -0.65804   2.6842    1.1952    1.     ]]


In [45]:
np.random.seed(0)

In [46]:
np.random.shuffle(data_orig)   #data shuffled

In [48]:
print(data_orig)

[[ -1.7713   -10.7665    10.2184    -1.0043     1.      ]
 [  5.1321    -0.031048   0.32616    1.1151     0.      ]
 [ -2.0149     3.6874    -1.9385    -3.8918     1.      ]
 ...
 [  0.6005     0.99945   -2.2126     0.097399   1.      ]
 [  2.0165    -0.25246    5.1707     1.0763     0.      ]
 [ -2.0759    10.8223     2.6439    -4.837      0.      ]]


In [49]:
print(data_orig.shape)

(1372, 5)


In [52]:
y_orig = data_orig[:,-1]

In [60]:
print(y_orig)

[1. 0. 1. ... 1. 0. 0.]


In [61]:
x_shuffled = data_orig[:,(0,1,2,3)].T

In [62]:
print(x_shuffled)
print(y_orig)

[[ -1.7713     5.1321    -2.0149   ...   0.6005     2.0165    -2.0759  ]
 [-10.7665    -0.031048   3.6874   ...   0.99945   -0.25246   10.8223  ]
 [ 10.2184     0.32616   -1.9385   ...  -2.2126     5.1707     2.6439  ]
 [ -1.0043     1.1151    -3.8918   ...   0.097399   1.0763    -4.837   ]]
[1. 0. 1. ... 1. 0. 0.]


In [66]:
x_shuffled_std = np.std(x_shuffled, axis=0, keepdims=True)
x_shuffled_mean = np.mean(x_shuffled,axis=0, keepdims=True)

In [71]:
print(x_shuffled_std)
print(x_shuffled_mean)

[[7.4450923  2.06087246 2.8389613  ... 1.24481073 1.99877325 5.93889466]]
[[-0.830925    1.635578   -1.03945    ... -0.12881275  2.00276
   1.638325  ]]


In [76]:
X = (x_shuffled - x_shuffled_mean)/x_shuffled_std


In [77]:
print(y_orig)

[1. 0. 1. ... 1. 0. 0.]


In [78]:
Y = y_orig

In [82]:
print(X.shape)

(4, 1372)


In [90]:
Y = np.reshape(Y,(Y.shape[0],1))
Y.shape


(1372, 1)